//@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNjMzMzM3NTgzLCJleHAiOjE2MzMzNDExODMsIm5iZiI6MTYzMzMzNzU4MywianRpIjoiNWg3eXIzekppQmFYYnp6MCIsInN1YiI6NCwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.UsYJA9bhNXw25gYXCUcgq7x6DAcr9_PEFIwbs_mHMo0

# get all
GET http://127.0.0.1:8000/api/movies/all HTTP/1.1
content-type: application/json

###

# create
POST http://127.0.0.1:8000/api/movie/create HTTP/1.1
content-type: application/json

{
  "title": "first test",
  "poster_image": "https://image.shutterstock.com/image-vector/smiley-vector-happy-face-260nw-465566966.jpg",
  "description": "bla bla bla"
}

###

# update
POST http://127.0.0.1:8000/api/movie/update/1 HTTP/1.1
content-type: application/json

{
  "title": "edit test 2"  
}

###

# delete
DELETE http://127.0.0.1:8000/api/movie/delete/8 HTTP/1.1
content-type: application/json

###

# show
GET http://127.0.0.1:8000/api/movie/show/8 HTTP/1.1
content-type: application/json