@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTY0MDU0NjMxNywiZXhwIjoxNjQwNTQ5OTE3LCJuYmYiOjE2NDA1NDYzMTcsImp0aSI6ImJQVGhhNjV6bjJlcjRHaDYiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.xTT8zoI5an-EXrxwcBVw4MpAldUuJBG596QD1u7f-F8

GET http://127.0.0.1:8000/api/moviereservations/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{ token }}

###

GET http://127.0.0.1:8000/api/moviereservations HTTP/1.1
content-type: application/json
Authorization: Bearer {{ token }}

###

GET http://127.0.0.1:8000/api/moviereservations/getReservations/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{ token }}

###

# login
POST http://127.0.0.1:8000/api/login HTTP/1.1
content-type: application/json

{
  "email": "osamayahya98@yahoo.com",
  "password": "veryNoice"
}

###

# logout
POST http://127.0.0.1:8000/api/logout HTTP/1.1
content-type: application/json

###

POST http://127.0.0.1:8000/api/moviereservations/create HTTP/1.1
content-type: application/json

{
  "date": "2020-12-14",
  "start_time": "2020-12-14 05:06:36",
  "end_time": "2020-12-14 07:07:58",
  "capacity": 20,
  "price": 7,
  "movie_id": 2
}

###

PUT http://127.0.0.1:8000/api/moviereservations/3 HTTP/1.1
content-type: application/json

{
  "capacity": 20
}

###

GET http://127.0.0.1:8000/api/moviereservations/reservation/1 HTTP/1.1
content-type: application/json

###

PUT http://127.0.0.1:8000/api/moviereservations/reserve/1 HTTP/1.1
content-type: application/json

{
  "id": 2,
  "seat_no": 3
}

###

PUT http://127.0.0.1:8000/api/moviereservations/delete/1 HTTP/1.1
content-type: application/json

{
  "id": 2
} 

###

DELETE http://127.0.0.1:8000/api/moviereservations/1 HTTP/1.1
content-type: application/json