@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTY0MDU0NjMxNywiZXhwIjoxNjQwNTQ5OTE3LCJuYmYiOjE2NDA1NDYzMTcsImp0aSI6ImJQVGhhNjV6bjJlcjRHaDYiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.xTT8zoI5an-EXrxwcBVw4MpAldUuJBG596QD1u7f-F8

GET http://127.0.0.1:8000/api/users/2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{ token }}

###

GET http://127.0.0.1:8000/api/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{ token }}

###

# login
POST http://127.0.0.1:8000/api/login HTTP/1.1
content-type: application/json

{
  "email": "iharris@example.org",
  "password": "secret"
}

###

# logout
POST http://127.0.0.1:8000/api/logout HTTP/1.1
content-type: application/json

###

POST http://127.0.0.1:8000/api/users/create HTTP/1.1
content-type: application/json

{
  "first_name": "Osama",
  "last_name": "Yahya",
  "username": "ossyahya98",
  "password": "veryNoice",
  "email": "osamayahya98@yahoo.com",
  "role": "customer",
  "mobile_number": "01025040565"
}

###


PUT http://127.0.0.1:8000/api/users/20 HTTP/1.1
content-type: application/json

{
  "first_name": "Osama"
}

###

DELETE http://127.0.0.1:8000/api/users/21 HTTP/1.1
content-type: application/json