@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTYzOTk2MDg4NywiZXhwIjoxNjM5OTY0NDg3LCJuYmYiOjE2Mzk5NjA4ODcsImp0aSI6InZEcjNCVVFiMG54eWE4a1EiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.cdRy6TO_1RrI0wj3dzlYqzIOkNUn2KghNCyZ-XCeKsA

GET http://127.0.0.1:8000/api/users/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{ token }}

###

# login
POST http://127.0.0.1:8000/api/login HTTP/1.1
content-type: application/json

{
  "email": "mallory52@example.net",
  "password": "secret"
}

###

POST http://127.0.0.1:8000/api/users/create HTTP/1.1
content-type: application/json

{
  "first_name": "Osama",
  "last_name": "Yahya",
  "username": "ossyahya98",
  "password": "veryNoice",
  "email": "osamayahya98@yahoo.com",
  "role": "customer",
  "mobile_number": "01025040565"
}