@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTY0MDExNDYwNCwiZXhwIjoxNjQwMTE4MjA0LCJuYmYiOjE2NDAxMTQ2MDQsImp0aSI6InY4WHVxQkVMdXA2Vms2cVoiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.mQwj05ab2Je76EJfq6tbqOlAfO7ysmFM4DYiFHsEn48

GET http://127.0.0.1:8000/api/users/1 HTTP/1.1
content-type: application/json

###

# login
POST http://127.0.0.1:8000/api/login HTTP/1.1
content-type: application/json

{
  "email": "mallory52@example.net",
  "password": "secret"
}

###

# logout
POST http://127.0.0.1:8000/api/logout HTTP/1.1
content-type: application/json

###

POST http://127.0.0.1:8000/api/users/create HTTP/1.1
content-type: application/json

{
  "first_name": "Osama",
  "last_name": "Yahya",
  "username": "ossyahya98",
  "password": "veryNoice",
  "email": "osamayahya98@yahoo.com",
  "role": "customer",
  "mobile_number": "01025040565"
}